export const vocabulary = {
  name: "nome",
  description: "descrição",
  cnpj: "CNPJ",
  email: "e-mail",
  office: "cargo",
  course: "curso",
  isActive: "ativo",
  enterprise: "empresa",
  enterpriseId: "empresa",
  weeklyWorkload: "carga horária semanal",
  profissionalProfile: "perfil profissional",
  workStyle: "estilo de trabalho",
  isPerson: "presencial",
  hybrid: "híbrido",
  remote: "remoto",
};
